---
dist: bionic
sudo: required
language: python
services:
  - docker
before_install:
  - sudo add-apt-repository -y ppa:wireguard/wireguard
  - sudo apt-get -qq update
  - sudo apt install linux-headers-$(uname -r)
  - sudo apt-get install -y wireguard-dkms
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
script:
  - molecule test